// import localFont from "next/font/local";
import ControlMenu from "./components/header";
import FooterPage from "./components/footer";
import './globals.css';

// import { Roboto } from 'next/font/google';



// const roboto = Roboto({
//   weight: '400',
//   subsets: ['latin'],
// });

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });

// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
      <ControlMenu />
      {/* Main Content */}
      <main className="min-h-screen">{children}</main>

      {/* Footer */}
     <FooterPage />
      </body>
    </html>

  );
}
