# Configuración para Cloudflare Pages
name = "gozamadrid-frontend-new"
compatibility_date = "2025-03-01"
pages_build_output_dir = "out"

# Configuración específica de compatibilidad
compatibility_flags = ["nodejs_compat"]

# Variables de entorno para producción
[vars]
# Variables API URLs 
NEXT_PUBLIC_API_URL = "https://realestatgozamadrid.com/api"
NEXT_PUBLIC_API_BASE_URL = "https://realestatgozamadrid.com"

# Configuración de timeouts y reintentos
NEXT_PUBLIC_API_TIMEOUT = "60000"
NEXT_PUBLIC_MAX_RETRIES = "8"
NEXT_PUBLIC_INITIAL_RETRY_DELAY = "1000"
NEXT_PUBLIC_MAX_RETRY_DELAY = "32000"

# Configuración de WordPress
NEXT_PUBLIC_WP_API_URL = "https://wordpress-1430059-5339263.cloudwaysapps.com/wp-json/wp/v2"
NEXT_PUBLIC_WC_API_URL = "https://wordpress-1430059-5339263.cloudwaysapps.com/wp-json/wc/v3"

# Configuración de caché
NEXT_PUBLIC_CACHE_MAX_AGE = "3600"
NEXT_PUBLIC_STALE_WHILE_REVALIDATE = "60"

# Configuración NODE
NODE_ENV = "production"

# Variables de entorno
ENVIRONMENT = "production"
MONGODB_API_URL = "http://gozamadrid-api-prod.eba-adypnjgx.eu-west-3.elasticbeanstalk.com"
USE_MONGODB_PROXY = "true"

# Configuración de bindings
[[kv_namespaces]]
  binding = "CACHE"
  id = "CACHE_KV_ID"

# Las siguientes variables contienen información sensible 
# y deben configurarse en el dashboard de Cloudflare, no aquí
# MONGODB_URI = "mongodb+srv://..."
# WOO_COMMERCE_KEY = "..."
# WOO_COMMERCE_SECRET = "..." 