// layout.js o RootLayout.js
import React, { Component } from 'react';
import FooterPage from '@/components/footer';
import ControlMenu from '@/components/header';
import '@/globals.css';
import Layout from '@/components/layout';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MyApp({ Component, pageProps }) {
    return (
      <Layout>
        <Component {...pageProps} />
      </Layout>
    );
  }



// src/pages/_app.js
